name: clean_and_bloc
description: Assignment Project for Impacteers.club.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  retrofit: ^4.0.1
  flutter_hooks: ^0.19.0
  cached_network_image: ^3.2.3
  ionicons: ^0.2.2
  dio:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: "SF Pro Text"
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Bold.otf
          weight: 700

